sudo mnexec -a 6686 iperf -s > /dev/null &
sudo mnexec -a 6697 iperf -s > /dev/null &
sudo mnexec -a 6709 iperf -s > /dev/null &
sudo mnexec -a 6727 iperf -s > /dev/null &
sudo mnexec -a 6738 iperf -s > /dev/null &
sudo mnexec -a 6748 iperf -s > /dev/null &
sudo mnexec -a 6765 iperf -s > /dev/null &
sudo mnexec -a 6775 iperf -s > /dev/null &
sudo mnexec -a 6790 iperf -s > /dev/null &
sudo mnexec -a 6801 iperf -s > /dev/null &
sudo mnexec -a 6813 iperf -s > /dev/null &
sudo mnexec -a 6826 iperf -s > /dev/null &
